version: "3.8"

services:
  backend:
    build:
      context: ./node-be
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: npm run dev

  frontend:
    build:
      context: ./react-fe
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      REACT_APP_API_URL: http://localhost:3000
